@baseUrl = http://localhost:3000

### Test base route
GET {{baseUrl}}/
Accept: text/plain

### Test database connection
GET {{baseUrl}}/test-db
Accept: application/json

### Test exemples route (list)
GET {{baseUrl}}/exemples
Accept: application/json

### Test exemples route (get by id)
GET {{baseUrl}}/exemples/67caffbed3e2f226fce33463
Accept: application/json

### Example of POST request
POST {{baseUrl}}/exemples
Content-Type: application/json

{
  "title": "Example item",
  "description": "This is a test item"
}

### Example of PUT request
PUT {{baseUrl}}/exemples/67caffbed3e2f226fce33463
Content-Type: application/json

{
  "title": "Updated example",
  "description": "This item has been updated"
}

### Example of DELETE request
DELETE {{baseUrl}}/exemples/67caffbed3e2f226fce33463
